### ISSUE TITLE
Permission denied to clone the contract

### ISSUE THREAD

**Issue by ccycv** [crypto-org-chain/cronos-smart-contract-example#1]
git clone git@github.com:crypto-org-chain/cronos-smart-contract-example.git
Cloning into 'cronos-smart-contract-example'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by kevglynn** [comment]
I had the same issue, but I replaced with the https clone link instead, and everything worked.

`git clone https://github.com/crypto-org-chain/cronos-smart-contract-example.git`
